[package]
name = "runes"
version = "0.1.0"
authors = ["Quinten van Woerkom <Quinten van Woerkom>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
